"""
forensic_report.py

This module is responsible for generating human-readable and machine-readable
forensic reports from metadata and image analysis results.

It supports:
- Text reports (for investigators / viva / court-style review)
- JSON reports (for ML pipelines, dashboards, or storage)

This module does NOT perform analysis.
It only PRESENTS results generated by other modules.
"""

from datetime import datetime
import json


# --------------------------------------------------
# Utility Helpers
# --------------------------------------------------

def safe_get(metadata, key, default="Unknown"):
    """
    Safely retrieve a value from metadata.

    - Handles missing keys
    - Handles empty strings
    - Ensures clean output in reports
    """
    try:
        value = metadata.get(key, default)
        if value is None or str(value).strip() == "":
            return default
        return value
    except Exception:
        return default


def parse_timestamp(ts):
    """
    Parse timestamps safely.

    Supports:
    - ISO format (from normalizer.py)
    - EXIF format (YYYY:MM:DD HH:MM:SS)
    """
    if not ts:
        return None

    try:
        return datetime.fromisoformat(ts)
    except ValueError:
        try:
            return datetime.strptime(ts, "%Y:%m:%d %H:%M:%S")
        except ValueError:
            return None


# --------------------------------------------------
# Timestamp Validation
# --------------------------------------------------

def check_timestamp_consistency(timestamps):
    """
    Check for inconsistencies and anomalies in timestamps.

    Returns:
    - List of human-readable issues
    """
    issues = []
    parsed_times = []

    if not timestamps:
        return issues

    # Parse all timestamps
    for field, ts in timestamps.items():
        parsed = parse_timestamp(ts)
        if parsed:
            parsed_times.append((field, parsed))
        else:
            issues.append(f"Invalid timestamp format: {field} → {ts}")

    # Check chronological order
    if len(parsed_times) > 1:
        sorted_times = sorted(parsed_times, key=lambda x: x[1])
        if parsed_times != sorted_times:
            issues.append("Timestamps are not in chronological order")

    return issues


# --------------------------------------------------
# Executive Summary
# --------------------------------------------------

def generate_executive_summary(analysis_result):
    """
    Generate a short, high-level summary for quick decision-making.
    """

    score = analysis_result.get("suspicion_score", 0)
    level = analysis_result.get("suspicion_level", "Unknown")
    flags = analysis_result.get("forensic_flags", [])

    summary = []
    summary.append("EXECUTIVE SUMMARY")
    summary.append("-" * 50)

    if level == "High":
        summary.append("❌ HIGH SUSPICION")
        summary.append("   Significant forensic anomalies detected")
        summary.append("   Immediate investigation recommended")
    elif level == "Medium":
        summary.append("⚠ MEDIUM SUSPICION")
        summary.append("   Some anomalies detected")
        summary.append("   Manual review advised")
    else:
        summary.append("✅ LOW SUSPICION")
        summary.append("   No major anomalies detected")
        summary.append("   Image likely authentic")

    summary.append(f"   Suspicion Score : {score}")
    summary.append(f"   Total Flags    : {len(flags)}")

    return "\n".join(summary)


# --------------------------------------------------
# Recommendations Engine
# --------------------------------------------------

def generate_recommendations(analysis_result):
    """
    Generate actionable forensic recommendations based on detected flags.
    """

    flags = analysis_result.get("forensic_flags", [])
    recs = []

    recs.append("RECOMMENDATIONS")
    recs.append("-" * 50)

    if not flags:
        recs.append("✓ No further action required")
        recs.append("  Image appears consistent and authentic")
        return "\n".join(recs)

    # Categorize flags
    for flag in flags:
        text = str(flag).lower()

        if "software" in text or "edited" in text:
            recs.append("⚠ SOFTWARE EDITING DETECTED")
            recs.append("  - Perform pixel-level manipulation analysis")
            recs.append("  - Check for cloning or content-aware fill")

        if "timestamp" in text or "chrono" in text:
            recs.append("⚠ TIMESTAMP ANOMALIES")
            recs.append("  - Compare with filesystem timestamps")
            recs.append("  - Verify event timeline consistency")

        if "compression" in text or "jpeg" in text:
            recs.append("⚠ COMPRESSION ANOMALIES")
            recs.append("  - Check for multiple re-save cycles")
            recs.append("  - Analyze quantization tables")

        if "gps" in text or "location" in text:
            recs.append("⚠ GPS / LOCATION ISSUES")
            recs.append("  - Cross-check coordinates with maps")
            recs.append("  - Validate timezone vs capture time")

    recs.append("")
    recs.append("🔍 ADVANCED ANALYSIS SUGGESTED")
    recs.append("  - Error Level Analysis (ELA)")
    recs.append("  - Noise pattern consistency")
    recs.append("  - Camera fingerprint comparison")

    return "\n".join(dict.fromkeys(recs))  # Remove duplicates


# --------------------------------------------------
# Main Report Generator
# --------------------------------------------------

def generate_forensic_report(analysis_result, output_file=None, format="txt"):
    """
    Generate a complete forensic report.

    Parameters:
    - analysis_result : dict (output from normalizer.py)
    - output_file     : optional file path
    - format          : 'txt' or 'json'

    Returns:
    - Report as string (text or JSON)
    """

    meta = analysis_result.get("normalized_metadata", {})
    flags = analysis_result.get("forensic_flags", [])
    insights = analysis_result.get("forensic_insights", {})
    timestamps = meta.get("Timestamps", {})

    # ---------------- TEXT REPORT ----------------
    if format.lower() == "txt":
        report = []

        report.append("=" * 70)
        report.append("IMAGE FORENSIC ANALYSIS REPORT")
        report.append("=" * 70)
        report.append(f"Generated : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        report.append("")

        # Executive Summary
        report.append(generate_executive_summary(analysis_result))
        report.append("")

        # Basic Info
        report.append("BASIC INFORMATION")
        report.append("-" * 50)
        report.append(f"Camera     : {safe_get(meta, 'Make')} {safe_get(meta, 'Model')}")
        report.append(f"Resolution : {safe_get(meta, 'Resolution')}")
        report.append(f"Software   : {safe_get(meta, 'Software')}")
        report.append("")

        # Timestamps
        if timestamps:
            report.append("TIMESTAMPS")
            report.append("-" * 50)
            for k, v in timestamps.items():
                report.append(f"{k:20} : {v}")

            issues = check_timestamp_consistency(timestamps)
            if issues:
                report.append("")
                report.append("⚠ TIMESTAMP ISSUES")
                for issue in issues:
                    report.append(f"  - {issue}")
            report.append("")

        # Forensic Flags
        report.append(f"FORENSIC FLAGS ({len(flags)})")
        report.append("-" * 50)
        if flags:
            for i, flag in enumerate(flags, 1):
                report.append(f"{i}. ⚠ {flag}")
        else:
            report.append("✓ No suspicious indicators detected")
        report.append("")

        # Insights
        if insights:
            report.append("FORENSIC INSIGHTS")
            report.append("-" * 50)
            for k, v in insights.items():
                report.append(f"{k}: {v}")
            report.append("")

        # Recommendations
        report.append(generate_recommendations(analysis_result))
        report.append("")

        # Final Verdict
        report.append("FINAL VERDICT")
        report.append("-" * 50)
        report.append(f"Suspicion Score : {analysis_result.get('suspicion_score')}")
        report.append(f"Suspicion Level : {analysis_result.get('suspicion_level')}")
        report.append("=" * 70)

        report_text = "\n".join(report)

        if output_file:
            with open(output_file, "w", encoding="utf-8") as f:
                f.write(report_text)

        return report_text

    # ---------------- JSON REPORT ----------------
    else:
        structured = {
            "generated": datetime.now().isoformat(),
            "summary": {
                "score": analysis_result.get("suspicion_score"),
                "level": analysis_result.get("suspicion_level"),
                "total_flags": len(flags),
            },
            "basic_information": meta,
            "timestamps": timestamps,
            "forensic_flags": flags,
            "forensic_insights": insights,
            "recommendations": generate_recommendations(analysis_result).split("\n"),
        }

        report_json = json.dumps(structured, indent=2, default=str)

        if output_file:
            with open(output_file, "w", encoding="utf-8") as f:
                f.write(report_json)

        return report_json
